### ISSUE TITLE
Problem Installing

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [Cldfire/mc-server-wrapper#3] opened 2021-02-11 21:17 UTC
Whenever I attempt to install this I've had problems I've been able to fix all of them except for one, which is whenever I attempt to install it after a while it says "could not find 'export' in syn'. If you can help that'd be great. I'm using the cargo install --git https://github.com/Cldfire/mc-server-wrapper.git method to install by the way.

**Comment by Cldfire** [comment] 2021-02-11 22:01
Interesting, sorry you're bumping into this!

I can reproduce it locally as well:

```
   Compiling minecraft-protocol-derive v0.0.0
error[E0432]: unresolved import `syn::export`
 --> /Users/work1pass/.cargo/registry/src/github.com-1ecc6299db9ec823/minecraft-protocol-derive-0.0.0/src/lib.rs:8:10
  |
8 | use syn::export::Span;
  |          ^^^^^^ could not find `export` in `syn`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `minecraft-protocol-derive`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
```

It looks like it's updating the `Cargo.lock` file prior to compiling because the `Cargo.lock` file specifies `futures v0.3.9` somewhere, which was yanked from crates.io. That's also updating `syn` which changed in a way that breaks `minecraft-protocol-derive` (a depedency I'd love to completely get rid of to begin with).

For now you can do `cargo install --git https://github.com/Cldfire/mc-server-wrapper.git --locked`, which will prevent the `Cargo.lock` update and allow compilation to succeed. I'll look into resolving the issue tonight.

**Comment by ATXLtheAxolotl** [comment] 2021-02-11 22:03
Thanks I’ll let you know if it works

**Comment by ATXLtheAxolotl** [comment] 2021-02-11 22:07
Thanks It worked.

**Closed as completed** 2021-02-12 00:56 UTC
Labels: bug

**Comment by Cldfire** [comment] 2021-02-12 00:57
All fixed now, thanks again for the report.

Please feel free to file issues for any other difficulties you run into / any feedback you have :)
